NUMERO_ETUDIANT    17102012568001619

CIVILITE         M.
NOM              BELLEGARDE
PRENOM           JUSTE
DATE_NAISSANCE   2007_10_28
TELEPHONE_FIXE   0579896149
TELEPHONE_MOBILE 0729805365
EMAIL            juste@bellegarde.fr

VOIE             133 RUE DU VICOIN
CODE_POSTAL      79410
COMMUNE          SAINT-GELAIS

25/09/2024 - 5 - SyntaxError - unexpected EOF while parsing string literal - vérifier les chaînes de caractères non terminées
02/10/2024 - 4 - NameError - name 'prient' is not defined. Did you mean: 'print'? - écrire print
4/09/2024 - 3 - IndexError - array index out of range - assurez-vous que l'indice est dans les limites du tableau
25/11/2024 - 3 - SyntaxError - unexpected 'finally' without 'try' - ajouter un bloc try correspondant
04/11/2024 - 2 - NameError - name 'prient' is not defined. Did you mean: 'print'? - écrire print
08/11/2024 - 5 - SyntaxError - unexpected token 'and' - corriger la logique ou la syntaxe avec 'and'
25/11/2024 - 2 - SyntaxError - invalid syntax for set literal - vérifier la syntaxe des ensembles
08/11/2024 - 4 - TypeError - 'tuple' object does not support item assignment - remplacer le tuple par une liste pour pouvoir modifier les éléments
08/11/2024 - 4 - SyntaxError - 'return' outside function - placer 'return' à l'intérieur d'une fonction
12/11/2024 - 4 - TypeError - 'builtin_function_or_method' object is not iterable for valeur in dict2.values - mettre les parenthèses
02/12/2024 - 3 - Invalid argument - can't open file 'Z:\TP3\seance5.py*' - enlever *
18/11/2024 - 4 - Invalid argument - can't open file 'Z:\TP3\seance5.py*' - enlever *
02/10/2024 - 4 - IndentationError - expected an indented block after 'def' statement on line 6 - ajouter un bloc indenté après def
04/11/2024 - 5 - IndentationError - expected an indented block after 'class' definition on line 14 - ajouter une indentation après class
14/10/2024 - 5 - RuntimeError - Set changed size during iteration - faire une différence avec lui-même
18/11/2024 - 3 - KeyError - KeyError: (1, 2) - vérifier si le tuple (1, 2) est présent comme clé dans le dictionnaire
18/11/2024 - 3 - TypeError - 'str' object cannot be interpreted as an integer - convertir la chaîne de caractères en entier avant d'utiliser
25/09/2024 - 3 - NameError - name 'parametre' is not defined. Did you mean 'parameter'? - corriger en parameter
18/11/2024 - 1 - TypeError - 'set' object has no attribute 'replace' - enlever les {}
18/11/2024 - 1 - AttributeError - 'float' object has no attribute 'is_integer' - utiliser uniquement avec des objets float compatibles
12/11/2024 - 2 - SyntaxError - 'continue' not properly in loop - placer 'continue' à l'intérieur d'une boucle
4/09/2024 - 2 - SyntaxError - unterminated triple-quoted string literal - fermer la chaîne de caractères triple-quote
25/11/2024 - 2 - SyntaxError - expected '}' in dictionary literal - fermer les accolades dans le dictionnaire
25/11/2024 - 2 - TypeError - 'builtin_function_or_method' object is not iterable for valeur in dict2.values - mettre les parenthèses
12/11/2024 - 1 - NameError - name 'enviroment' is not defined. Did you mean 'environment'? - corriger en environment
18/11/2024 - 2 - TypeError - unsupported operand type(s) for /: 'str' and 'int' - convertir la chaîne en entier ou flottant avant de diviser
08/11/2024 - 5 - SyntaxError - unexpected EOF while parsing - vérifier la fermeture des blocs ou parenthèses
25/11/2024 - 1 - IndentationError - expected an indented block after function definition on line 28 - respecter les indentations
18/11/2024 - 4 - ZeroDivisionError - integer division or modulo by zero - la division par zéro est impossible
04/11/2024 - 3 - NameError - name 'liste3' is not defined. Did you mean: 'liste1'? - écrire liste1
25/11/2024 - 1 - SyntaxError - 'continue' not properly in loop - placer 'continue' à l'intérieur d'une boucle
04/11/2024 - 4 - NameError - name 'confiq' is not defined. Did you mean 'config'? - corriger en config
25/09/2024 - 2 - SyntaxError - unexpected token 'and' - corriger la logique ou la syntaxe avec 'and'
25/11/2024 - 1 - NameError - name 'true' is not defined. Did you mean 'True'? - écrire True
02/12/2024 - 2 - IndexError - index out of range in self - corriger l'indice pour qu'il soit dans les limites de l'objet
18/11/2024 - 3 - SyntaxError - 'continue' not properly in loop - placer 'continue' à l'intérieur d'une boucle
04/11/2024 - 1 - KeyError - KeyError: 'name' - vérifier si la clé 'name' existe dans le dictionnaire